require 'pry'
require 'dotenv'
Dotenv.load

PRIME = 1038211
BASE = 1000

require 'set'

require_relative 'hackerrank'
require_relative 'inverse_module'
require_relative 'rolling_hash'
require_relative 'rabin_karp_search'
require_relative 'grid_search'
require_relative 'matrix_rotation'
require_relative 'create_suffix_array'
require_relative 'create_suffix_array_with_sorting'
require_relative 'suffix_tree_node'
require_relative 'create_suffix_array_with_tree'
require_relative 'create_inverted_suffix_array'
require_relative 'suffix_array_member'
require_relative 'suffix_array_search'
require_relative 'red_black_tree_node'
require_relative 'red_black_nil_node'
require_relative 'red_black_tree'
require_relative 'binary_indexed_tree'
require_relative 'next_permutation'
require_relative 'quick_sort'
require_relative 'merge_sort'
require_relative 'min_heap'
require_relative 'prim_undirected_graph'
require_relative 'edge'
require_relative 'floyd_directed_graph'
require_relative 'floyd_shortest_path'
require_relative 'boyer_moore_horspool'
require_relative 'save_humanity'
